"""Add extracted_description to JobDetails

Revision ID: 21951a5d4784
Revises: 3efff8188b58
Create Date: 2026-03-09 21:59:13.566971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21951a5d4784'
down_revision: Union[str, Sequence[str], None] = '3efff8188b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobdetails', sa.Column('extracted_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobdetails', 'extracted_description')
    # ### end Alembic commands ###
