"""Add is_stub to VCFirm

Revision ID: 2e05ed1016ca
Revises: d56b5de5b389
Create Date: 2026-03-07 01:44:28.579349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e05ed1016ca'
down_revision: Union[str, Sequence[str], None] = 'd56b5de5b389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('vcfirm', sa.Column('is_stub', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vcfirm', 'is_stub')
    # ### end Alembic commands ###
