"""add_needs_deep_scrape_and_job_details

Revision ID: 3efff8188b58
Revises: 8098a92b5d5e
Create Date: 2026-03-09 19:10:32.711026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3efff8188b58'
down_revision: Union[str, Sequence[str], None] = '8098a92b5d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobdetails',
    sa.Column('description_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_benefits', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobdetails_job_id'), 'jobdetails', ['job_id'], unique=True)
    op.add_column('job', sa.Column('needs_deep_scrape', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index(op.f('ix_job_needs_deep_scrape'), 'job', ['needs_deep_scrape'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_needs_deep_scrape'), table_name='job')
    op.drop_column('job', 'needs_deep_scrape')
    op.drop_index(op.f('ix_jobdetails_job_id'), table_name='jobdetails')
    op.drop_table('jobdetails')
    # ### end Alembic commands ###
