"""Initial schema

Revision ID: 4a9a5351c9f0
Revises: 
Create Date: 2026-03-06 15:57:34.656045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a9a5351c9f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('company',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_funding_usd', sa.Float(), nullable=True),
    sa.Column('last_funding_round', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('investors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_index(op.f('ix_company_tenant_id'), 'company', ['tenant_id'], unique=False)
    op.create_table('job',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('salary_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('experience_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('normalized_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('normalized_seniority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('functional_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_company_id'), 'job', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_tenant_id'), 'job', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_index(op.f('ix_job_tenant_id'), table_name='job')
    op.drop_index(op.f('ix_job_company_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_company_tenant_id'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
