"""add last_content_hash to company

Revision ID: 8098a92b5d5e
Revises: d5cc891eceda
Create Date: 2026-03-09 10:08:32.217316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8098a92b5d5e'
down_revision: Union[str, Sequence[str], None] = 'd5cc891eceda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('last_content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'last_content_hash')
    # ### end Alembic commands ###
