"""add last_scraped_at to company

Revision ID: 8b554d7c87cf
Revises: 4a9a5351c9f0
Create Date: 2026-03-06 17:29:36.716986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b554d7c87cf'
down_revision: Union[str, Sequence[str], None] = '4a9a5351c9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('last_scraped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'last_scraped_at')
    # ### end Alembic commands ###
