"""add growth signals to company model

Revision ID: a1be32f76b8a
Revises: 2e05ed1016ca
Create Date: 2026-03-08 21:58:26.263990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1be32f76b8a'
down_revision: Union[str, Sequence[str], None] = '2e05ed1016ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('last_funding_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('employee_count', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('founded_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'founded_date')
    op.drop_column('company', 'employee_count')
    op.drop_column('company', 'last_funding_amount')
    # ### end Alembic commands ###
