"""Add ExecutionLog and JobDetails

Revision ID: b50f6f783baa
Revises: 21951a5d4784
Create Date: 2026-03-10 19:50:33.667059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b50f6f783baa'
down_revision: Union[str, Sequence[str], None] = '21951a5d4784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executionlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executionlog_company_id'), 'executionlog', ['company_id'], unique=False)
    op.create_index(op.f('ix_executionlog_created_at'), 'executionlog', ['created_at'], unique=False)
    op.create_index(op.f('ix_executionlog_job_id'), 'executionlog', ['job_id'], unique=False)
    op.drop_index(op.f('ix_scrapetask_company_id'), table_name='scrapetask')
    op.drop_table('scrapetask')
    op.drop_column('job', 'normalized_seniority')
    op.alter_column('vcfirm', 'website_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vcfirm', 'website_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('job', sa.Column('normalized_seniority', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('scrapetask',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('scrapetask_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scrapetask_pkey'))
    )
    op.create_index(op.f('ix_scrapetask_company_id'), 'scrapetask', ['company_id'], unique=False)
    op.drop_index(op.f('ix_executionlog_job_id'), table_name='executionlog')
    op.drop_index(op.f('ix_executionlog_created_at'), table_name='executionlog')
    op.drop_index(op.f('ix_executionlog_company_id'), table_name='executionlog')
    op.drop_table('executionlog')
    # ### end Alembic commands ###
