"""Epic 2: Add Junction table and Differential Ingestion fields

Revision ID: bd6ebe140987
Revises: deb1bc041c13
Create Date: 2026-03-06 22:43:47.584798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd6ebe140987'
down_revision: Union[str, Sequence[str], None] = 'deb1bc041c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companyvcfirmlink',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('vc_firm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['vc_firm_id'], ['vcfirm.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'vc_firm_id')
    )
    op.drop_column('company', 'investors')
    op.add_column('vcfirm', sa.Column('portfolio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vcfirm', sa.Column('portfolio_html_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vcfirm', sa.Column('last_scraped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vcfirm', 'last_scraped_at')
    op.drop_column('vcfirm', 'portfolio_html_hash')
    op.drop_column('vcfirm', 'portfolio_url')
    op.add_column('company', sa.Column('investors', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('companyvcfirmlink')
    # ### end Alembic commands ###
