"""Add Crunchbase columns

Revision ID: d56b5de5b389
Revises: bd6ebe140987
Create Date: 2026-03-07 01:37:01.123966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd56b5de5b389'
down_revision: Union[str, Sequence[str], None] = 'bd6ebe140987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('total_funding_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('last_funding_date', sa.DateTime(), nullable=True))
    op.add_column('company', sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('industries', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('estimated_revenue_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('cb_rank', sa.Integer(), nullable=True))
    op.drop_column('company', 'total_funding_usd')
    op.add_column('vcfirm', sa.Column('num_portfolio_orgs', sa.Integer(), nullable=True))
    op.add_column('vcfirm', sa.Column('investor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vcfirm', sa.Column('num_investments', sa.Integer(), nullable=True))
    op.add_column('vcfirm', sa.Column('num_exits', sa.Integer(), nullable=True))
    op.add_column('vcfirm', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vcfirm', sa.Column('cb_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vcfirm', 'cb_rank')
    op.drop_column('vcfirm', 'location')
    op.drop_column('vcfirm', 'num_exits')
    op.drop_column('vcfirm', 'num_investments')
    op.drop_column('vcfirm', 'investor_type')
    op.drop_column('vcfirm', 'num_portfolio_orgs')
    op.add_column('company', sa.Column('total_funding_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('company', 'cb_rank')
    op.drop_column('company', 'estimated_revenue_range')
    op.drop_column('company', 'location')
    op.drop_column('company', 'industries')
    op.drop_column('company', 'stage')
    op.drop_column('company', 'last_funding_date')
    op.drop_column('company', 'total_funding_amount')
    # ### end Alembic commands ###
