"""make company website_url nullable and unique

Revision ID: d5cc891eceda
Revises: 9e355cba9a88
Create Date: 2026-03-08 23:05:11.220993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5cc891eceda'
down_revision: Union[str, Sequence[str], None] = '9e355cba9a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'website_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # Data cleanup: Convert '#' to NULL so the unique index can be created
    op.execute("UPDATE company SET website_url = NULL WHERE website_url = '#'")
    op.create_index(op.f('ix_company_website_url'), 'company', ['website_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_website_url'), table_name='company')
    op.alter_column('company', 'website_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
